using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WPFMessengePrototype.FakeData;

public static class FakeDatas
{
    public static string LoremIpsum { get; set; } = @"Proin venenatis nulla nec lorem rutrum, quis tincidunt ante ornare. Donec elit nisi, vestibulum id eros ac, fringilla sollicitudin odio. Sed tristique lacinia nunc eget finibus. Sed sit amet venenatis erat, lacinia ultricies ipsum. Nam volutpat vestibulum lectus, ut bibendum diam suscipit non. Vestibulum sit amet dolor vitae lorem semper porta non non nisl. Nullam pulvinar eros eu nibh malesuada, id dignissim justo consectetur. Sed elit nulla, imperdiet sed mollis eget, venenatis ut urna. Aliquam tempor mattis tempus. Aliquam erat volutpat. Sed sed nulla eget nibh cursus ultricies in ac lacus. Donec augue neque, tempus quis ullamcorper eleifend, viverra ut eros.
Donec sit amet nisi sit amet diam luctus viverra. Ut in tristique magna. Vivamus consectetur magna porta odio hendrerit tincidunt. Nulla pretium at quam vitae laoreet. In a turpis aliquam, laoreet orci quis, scelerisque dolor. Morbi sem ipsum, lacinia at quam id, tempus lacinia purus. Proin ut libero eget dui accumsan pellentesque at sed ipsum. Pellentesque sollicitudin, lorem ac egestas accumsan, arcu diam hendrerit risus, sed pulvinar dui metus eu nisl. Nullam et aliquet purus.
In vitae ligula purus. Integer bibendum enim id pretium congue. Etiam lobortis feugiat justo, id pretium sapien iaculis vitae. Nulla dolor diam, dictum nec nisl sed, vestibulum cursus erat. Aenean egestas, felis vitae congue fringilla, nisi neque posuere nisl, nec varius massa nisl ut risus. Morbi pharetra lacus ut tempor porta. Aliquam erat volutpat.
Curabitur nunc leo, interdum sed lectus eu, tristique pretium nisl. Maecenas lacus tellus, sagittis id lacinia ac, dictum in felis. Duis et condimentum orci. Fusce eget mauris sit amet augue eleifend maximus. Pellentesque luctus nisl vitae odio aliquet, non mollis diam sollicitudin. Maecenas varius porta neque, non imperdiet lacus euismod et. Quisque lobortis lacinia ante sed imperdiet. Nullam porttitor, purus in eleifend porta, metus elit ultricies quam, sit amet finibus erat leo ut mi. Aenean pulvinar, dolor non facilisis commodo, dui nisl dictum nunc, sed maximus diam magna at orci. Vivamus id sapien a odio condimentum lacinia. Suspendisse non hendrerit ligula, id tincidunt augue. Nam tincidunt eros non dolor feugiat, et elementum leo bibendum. In et libero odio. Nunc varius non elit in ultricies.
Sed quis facilisis nibh, at rhoncus orci. Proin convallis nisl nisl, vel finibus mi sollicitudin ac. Praesent in massa quis orci egestas ultricies ut sed leo. Aliquam pulvinar euismod orci. Nunc vehicula ultrices interdum. Pellentesque egestas porttitor orci, at euismod enim auctor ut. Nunc finibus velit et sagittis consectetur.
Suspendisse potenti. Aenean fringilla, nisl in tempor finibus, elit turpis lobortis dui, vel placerat lectus eros sed metus. Mauris placerat, mauris in scelerisque laoreet, quam lectus varius ante, et ullamcorper nulla dui eu lectus. Nunc auctor, augue vitae pretium posuere, libero elit fringilla metus, vitae lacinia risus risus et nisi. Maecenas maximus lectus non elit vestibulum rhoncus. In hac habitasse platea dictumst. Pellentesque ante est, cursus in augue at, ultricies varius felis. Nam vehicula eros eleifend dui congue tempus. Cras eros justo, malesuada vitae facilisis id, viverra quis ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam felis lacus, pulvinar vel orci et, porta eleifend metus.
Nam in velit pellentesque, condimentum libero ut, aliquet lacus. Morbi congue diam odio, a egestas ex malesuada sed. Donec aliquet turpis id arcu tincidunt, et porta felis venenatis. Aliquam hendrerit eu diam ac vestibulum. Vivamus at consequat tortor. Etiam lobortis, nibh vitae dictum ultricies, lorem felis eleifend enim, eget vulputate dolor eros vitae ipsum. Ut vel est in dui luctus condimentum. Mauris id tincidunt mi, non condimentum felis. Aliquam tempus leo neque, id facilisis ex dapibus quis. Vivamus dolor dui, fringilla ut tincidunt sed, eleifend sit amet libero. Nullam vitae arcu pellentesque libero volutpat hendrerit in eget orci. Pellentesque dictum tortor at urna aliquam faucibus. Proin ut tincidunt est. Nunc id est molestie, varius lorem sed, scelerisque est. Cras a ipsum aliquam, facilisis purus malesuada, malesuada nisi.";
}
